# netlify.toml — valid TOML

[build]
  command = "npm install --no-audit --no-fund --loglevel verbose && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_OPTIONAL = "false"
  NPM_CONFIG_LOGLEVEL = "verbose"
  ROLLUP_DISABLE_NATIVE = "true"
  NETLIFY_BUILD_DEBUG = "true"

[functions]
  node_bundler = "esbuild"

# Mount any Netlify Functions under /api/*
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback for Vite app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
