[build]
  command = "npm install && npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# ✅ Send /api/* to your serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback (keep last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
