# netlify.toml
[build]
  command = "npm install && npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# If you ever fetch functions via /api/* in the client,
# this keeps those URLs working in production.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
