[build]
  command = "npm install --no-audit --no-fund --loglevel verbose && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  # Do NOT set external_node_modules here for googleapis
