[build]
  command = "npm install --no-audit --no-fund --loglevel verbose && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  # important: do NOT list googleapis here
  # external_node_modules = []


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
