[build]
  command = "npm install --no-audit --no-fund --loglevel verbose && npm run build"
  publish = "dist"

# Keep SPA fallback so React Router works
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
