# netlify.toml
[build]
  command = "npm install && npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Optional: support /api/* routing if your frontend calls /api/... 
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
